# ===== ОСНОВНЫЕ НАСТРОЙКИ =====
target-version = "py311"
line-length = 80
indent-width = 4

# Игнорируемые файлы и папки
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "migrations",
    "*.egg-info",
    "*.pyc",
    "*.so",
    "*.dll",
    "env",
    "venv",
]

# ===== ФОРМАТИРОВАНИЕ =====
[format]
# Агрессивное форматирование
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "auto"

# ===== LINTING =====
[lint]
# Включаем ВСЕ правила (по-хардкорному)
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort (сортировка импортов)
    "UP", # pyupgrade
    "ARG", # unused arguments
    "COM", # commas
    "ERA", # commented out code
    "FBT", # boolean trap
]
preview = true

ignore = [
    "E501",
    "C901", 
    "S101",
    "TRY003",
    "PLR0913",
    "PLR2004",
    "SLF001",
]

# Уровень строгости
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# ===== СПЕЦИФИЧЕСКИЕ НАСТРОЙКИ ПРАВИЛ =====
[lint.flake8-annotations]
suppress-none-returning = true
allow-star-arg-any = true

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "pydantic.Field"]


[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"
avoid-escape = true

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
known-first-party = ["app", "src", "tests"]
combine-as-imports = true
split-on-trailing-comma = true
order-by-type = true
force-wrap-aliases = true
lines-after-imports = 2
lines-between-types = 1

[lint.pylint]
allow-magic-value-types = ["float", "int", "str"]

[lint.pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.validator"]
staticmethod-decorators = ["staticmethod"]


# ===== НАСТРОЙКИ БЕЗОПАСНОСТИ =====
[lint.flake8-bandit]
check-typed-exception = true

# Настройки для конкретных правил
[lint.per-file-ignores]
"__init__.py" = ["F401"]
"migrations/*" = ["ALL"]

# ===== НАСТРОЙКИ СЛОЖНОСТИ =====
[lint.mccabe]
max-complexity = 10
